name: tcr-antigen-prediction
channels:
  - bioconda
  - salilab
  - conda-forge
  - nodefaults
dependencies:
  - dvc
  - h5py
  - hmmer
  - jupyter
  - modeller
  - pip
  - pygraphviz
  - python=3.11
  - snakemake
  - pip:
      - biopython
      - logomaker
      - matplotlib
      - networkx
      - numpy
      - onnxruntime
      - openchord
      - pandas
      - plotly
      - pyxdameraulevenshtein
      - seaborn
      - snakemake-executor-plugin-slurm
      - upsetplot
