[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tcr_antigen_prediction"
version = "0.0.0"
authors = [
    { name="Benjamin McMaster", email="benjamin.mcmaster@rdm.ox.ac.uk"}
]
requires-python = ">=3.10"
dependencies = [
    "biopython",
    "scikit-learn",
]

[project.optional-dependencies]
develop = [
    "flake8",
    "myst-parser",
    "pylint",
    "pytest",
    "prysk",
    "sphinx",
    "sphinx-rtd-theme",
]