name: Test package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install submodules
        run: |
            eval $(ssh-agent -s)
            ssh-add - <<< "${{ secrets.ANARCI_TCR_PMHC_SSH_KEY }}"
            git submodule init
            git submodule update --recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
            auto-activate-base: true
            activate-environment: ""
      - name: Setup environment
        run: |
            pip install pulp==2.7.0 snakemake
            snakemake environment --quiet all --cores 1
            conda run -n tcr-antigen-prediction pip install '.[develop]'
      - name: Lint package
        run: conda run -n tcr-antigen-prediction snakemake lint --quiet all
      - name: Test package
        run: conda run -n tcr-antigen-prediction snakemake test --quiet all
